
import uvicorn
from fastapi import FastAPI, APIRouter
from fastapi.middleware.cors import CORSMiddleware
from fastapi.openapi.utils import get_openapi
from fastapi.openapi.docs import get_swagger_ui_html

from config import settings
from auth_router import auth_router as jwt_auth_router, users_router
from sessions_router import router as sessions_router
from recordings_router import router as recordings_router
from datasets_router import router as datasets_router
from blocos_router import router as blocos_router
from frases_router import router as frases_router
from admin_router import router as admin_router
from musics_router import router as musics_router

app = FastAPI(
    title=settings.APP_NAME,
    version="1.0.0",
    description="API for collecting speech datasets.",
    docs_url=None,
    redoc_url=None,
    openapi_url=None
)

@app.get("/docs", include_in_schema=False)
async def get_documentation():
    return get_swagger_ui_html(openapi_url="/openapi.json", title="API Documentation")

@app.get("/openapi.json", include_in_schema=False)
async def get_open_api_endpoint():
    return custom_openapi()

def custom_openapi():
    """Build OpenAPI while preserving security generated by dependencies."""
    if app.openapi_schema:
        return app.openapi_schema
    openapi_schema = get_openapi(
        title=app.title,
        version=app.version,
        description=app.description,
        routes=app.routes,
    )
    app.openapi_schema = openapi_schema
    return app.openapi_schema

app.openapi = custom_openapi

# CORS Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ALLOWED_ORIGINS,
    allow_credentials="*" not in settings.CORS_ALLOWED_ORIGINS,
    allow_methods=["*"],
    allow_headers=["*"],
)

# API Routers
app.include_router(jwt_auth_router, prefix="/auth")
app.include_router(users_router, prefix="/users")
app.include_router(admin_router)

# Group all v1 API routers under a single prefix
api_v1_router = APIRouter(prefix="/api/v1")
api_v1_router.include_router(sessions_router)
api_v1_router.include_router(datasets_router)
api_v1_router.include_router(blocos_router)
api_v1_router.include_router(frases_router)
api_v1_router.include_router(recordings_router)
api_v1_router.include_router(musics_router)
app.include_router(api_v1_router)


@app.get("/")
def read_root():
    return {"message": f"Welcome to {settings.APP_NAME}"}

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)

