events {}

http {
    client_max_body_size 100M;
    server {
        listen 80;
        server_name localhost 34.204.18.104;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost 34.204.18.104;

        ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

        location / {
            # CORS is handled by the FastAPI application
            proxy_pass http://app:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}