version = 5.4.0
archive_dir = /etc/letsencrypt/archive/akcitapi.duckdns.org
cert = /etc/letsencrypt/live/akcitapi.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/akcitapi.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/akcitapi.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/akcitapi.duckdns.org/fullchain.pem
[renewalparams]
account = e8290bb0bc31f4160d826cba5774bbe8
authenticator = webroot
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
akcitapi.duckdns.org = /var/www/certbot
